"""create user table

Revision ID: 0697e6549bbe
Revises: bfed468d38c1
Create Date: 2026-04-08 21:42:57.514475

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0697e6549bbe"
down_revision: Union[str, Sequence[str], None] = "bfed468d38c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.Column("nickname", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.Column("birth", sa.Date(), nullable=True),
        sa.Column("phone_num", sa.String(length=128), nullable=True),
        sa.Column("phone_hash", sa.String(length=128), nullable=True),
        sa.Column("provider", sa.String(length=10), nullable=False),
        sa.Column("social_id", sa.String(length=128), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_hash"),
        sa.UniqueConstraint("social_id"),
    )
    op.create_index(
        "ix_active_user_recovery",
        "users",
        ["name", "birth", "phone_hash"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("ix_user_created_at", "users", [sa.literal_column("created_at DESC")], unique=False)
    op.create_index("ix_user_nickname_lower", "users", [sa.literal_column("lower(nickname)")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_nickname_lower", table_name="users")
    op.drop_index("ix_user_created_at", table_name="users")
    op.drop_index("ix_active_user_recovery", table_name="users", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_table("users")
    # ### end Alembic commands ###
