"""Initial migration

Revision ID: a13a18a29ced
Revises:
Create Date: 2026-04-07 02:06:51.191690

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a13a18a29ced"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
