"""create user table

Revision ID: bfed468d38c1
Revises: a13a18a29ced
Create Date: 2026-04-08 21:40:38.900185

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "bfed468d38c1"
down_revision: Union[str, Sequence[str], None] = "a13a18a29ced"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
